import { Avatar } from "@/enums"

const svgUrlByAvatar = new Map<Avatar, string>([
    [Avatar.AfroBusinessMan, "/afro-business-man.svg"],
    [Avatar.AfroBusinessWoman, "/afro-business-woman.svg"],
    [Avatar.AfroFemaleFarmer, "/afro-female-farmer.svg"],
    [Avatar.AfroFemaleGraduatedStudent, "/afro-female-graduated-student.svg"],
    [Avatar.AfroFemaleScientist, "/afro-female-scientist.svg"],
    [Avatar.AfroMaleFarmer, "/afro-male-farmer.svg"],
    [Avatar.AfroMaleGraduatedStudent, "/afro-male-graduated-student.svg"],
    [Avatar.AfroMaleScientist, "/afro-male-scientist.svg"],
    [Avatar.AfroMan, "/afro-man.svg"],
    [Avatar.AfroOldBusinessMan, "/afro-old-business-man.svg"],
    [Avatar.AfroOldBusinessWoman, "/afro-old-business-woman.svg"],
    [Avatar.AfroOldFemaleFarmer, "/afro-old-female-farmer.svg"],
    [Avatar.AfroOldMaleFarmer, "/afro-old-male-farmer.svg"],
    [Avatar.AfroOldMan, "/afro-old-man.svg"],
    [Avatar.AfroOldSportMan, "/afro-old-sport-man.svg"],
    [Avatar.AfroOldSportWoman, "/afro-old-sport-woman.svg"],
    [Avatar.AfroSportMan, "/afro-sport-man.svg"],
    [Avatar.AfroSportWoman, "/afro-sport-woman.svg"],
    [Avatar.AfroWoman, "/afro-woman.svg"],
    [Avatar.AfroYoungMan, "/afro-young-man.svg"],
    [Avatar.AfroYoungWoman, "/afro-young-woman.svg"],
    [Avatar.AsianOldMan, "/asian-old-man.svg"],
    [Avatar.AsianOldWoman, "/asian-old-woman.svg"],
    [Avatar.AsianYoungWoman, "/asian-young-woman.svg"],
    [Avatar.BusinessMan, "/business-man.svg"],
    [Avatar.BusinessWoman, "/business-woman.svg"],
    [Avatar.Clown, "/clown.svg"],
    [Avatar.Criminal, "/criminal.svg"],
    [Avatar.FemaleFarmer, "/female-farmer.svg"],
    [Avatar.FemaleGraduatedStudent, "/female-graduated-student.svg"],
    [Avatar.FemaleScientist, "/female-scientist.svg"],
    [Avatar.FireFighter, "/fire-fighter.svg"],
    [Avatar.Hoodie, "/hoodie.svg"],
    [Avatar.IndianWoman, "/indian-woman.svg"],
    [Avatar.MaleArtist, "/male-artist.svg"],
    [Avatar.MaleFarmer, "/male-farmer.svg"],
    [Avatar.MaleMuslim, "/male-muslim.svg"],
    [Avatar.MaleScientist, "/male-scientist.svg"],
    [Avatar.MuslimMan, "/muslim-man.svg"],
    [Avatar.OldBusinessMan, "/old-business-man.svg"],
    [Avatar.OldBusinessWoman, "/old-business-woman.svg"],
    [Avatar.OldFemaleFarmer, "/old-female-farmer.svg"],
    [Avatar.OldMaleFarmer, "/old-male-farmer.svg"],
    [Avatar.OldMan, "/old-man.svg"],
    [Avatar.OldSportMan, "/old-sport-man.svg"],
    [Avatar.OldSportWoman, "/old-sport-woman.svg"],
    [Avatar.OldWoman, "/old-woman.svg"],
    [Avatar.PartyMan, "/party-man.svg"],
    [Avatar.PartyWoman, "/party-woman.svg"],
    [Avatar.SportMan, "/sport-man.svg"],
    [Avatar.SportWoman, "/sport-woman.svg"],
    [Avatar.YoungMan, "/young-man.svg"],
])

export const getSvgUrlByAvatar = (avatar: Avatar): string => (
    svgUrlByAvatar.get(avatar) ?? ""
)
